CREATE TABLE property (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid BINARY(16) NOT NULL UNIQUE,
    registration VARCHAR(255) NOT NULL UNIQUE,
    property_kind VARCHAR(255) NOT NULL,
    property_leisure_items TEXT NOT NULL,
    country VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    city VARCHAR(100) NOT NULL,
    neighborhood VARCHAR(150),
    zipcode VARCHAR(50) NOT NULL,
    street_name VARCHAR(255) NOT NULL,
    house_number INT NOT NULL,
    complement VARCHAR(100),
    land_size INT NOT NULL,
    building_area INT NOT NULL,
    garage INT NOT NULL,
    rooms INT NOT NULL,
    isRent BOOLEAN,
    rentPrice DECIMAL(19, 2),
    isSale BOOLEAN,
    salePrice DECIMAL(19, 2),
    isFurnished BOOLEAN,
    taxes DECIMAL(19, 2) NOT NULL,
    isCondominium BOOLEAN,
    condominium_price DECIMAL(19, 2),
    condominium_leisure_items TEXT NOT NULL,
    description TEXT NOT NULL
);